# Use an official Node runtime as a parent image
FROM node:20-slim

# Set the working directory in the container
WORKDIR /app

# Copy package files
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the frontend code
COPY frontend/ .

# Expose the port the app runs on
EXPOSE 5173

# Start the application in dev mode
CMD ["npm", "run", "dev", "--", "--host"]
